addons:
  postgresql: "9.6"
rvm:
  - 2.3.0
  - 2.4.0
  - 2.5.0
  - 2.6.0
gemfile:
  - gemfiles/rails_5.0.gemfile
  - gemfiles/rails_5.1.gemfile
  - gemfiles/rails_5.2.gemfile
  - gemfiles/rails_6.0.gemfile
matrix:
  exclude:
  - rvm: 2.3.0
    gemfile: gemfiles/rails_6.0.gemfile
  - rvm: 2.4.0
    gemfile: gemfiles/rails_6.0.gemfile
before_install:
  - gem install --force bundler -v 1.17.3
script:
  - bundle _1.17.3_ exec spec/dummy/bin/rake db:create RAILS_ENV=test --rakefile=spec/dummy/Rakefile
  - bundle _1.17.3_ exec rubocop
  - bundle _1.17.3_ exec rspec
