default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: active_record-postgres-constraints-development

test:
  <<: *default
  database: active_record-postgres-constraints-test<%= ENV['TEST_ENV_NUMBER'] %>
  migrations_paths:
    - spec/dummy/db/migrate<%= ENV['TEST_ENV_NUMBER'] %>
